"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class digital_t(object):
    __slots__ = ["name", "value"]

    def __init__(self):
        self.name = ""
        self.value = False

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(digital_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write("\0")
        buf.write(struct.pack(">b", self.value))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != digital_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return digital_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = digital_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.value = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if digital_t in parents: return 0
        tmphash = (0x3bdedce7d49bfde8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if digital_t._packed_fingerprint is None:
            digital_t._packed_fingerprint = struct.pack(">Q", digital_t._get_hash_recursive([]))
        return digital_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

